-- backend schema setup for Supabase (Postgres + pgvector)
-- Run in Supabase SQL editor.
-- This script manages only the objects owned by this app: the courses
-- catalogue, the roadmaps table, and the match_courses vector-search function.
-- public.users and public.user_skill_details are maintained by Team 1 and are
-- referenced by roadmaps but are NOT created or dropped here.


-- Extensions
create extension if not exists "pgcrypto";
create extension if not exists "vector";

-- =========================
-- courses (independent catalogue)
-- =========================
-- Courses are standalone objects. They are not linked to users or skills.
create table if not exists public.courses (
    course_id           uuid primary key default gen_random_uuid(),
    course_name         varchar(255) not null,
    provider            varchar(100),
    external_course_id  varchar(100),
    description         text,
    category            varchar(100),
    difficulty_level    varchar(20),
    duration_hours      numeric(6, 2),
    url                 varchar(500),
    prerequisites       jsonb,
    skills_taught       jsonb,
    rating              numeric(3, 2),
    enrollment_count    integer,
    embedding           vector(768),
    created_at          timestamptz default now()
);

create index if not exists ix_courses_external_course_id
  on public.courses (external_course_id);

-- Vector similarity index (cosine distance)
-- Note: for ivfflat to be effective, you typically need data before meaningful performance gains.
create index if not exists ix_courses_embedding
  on public.courses
  using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

-- RPC: match_courses (safe to recreate)
create or replace function public.match_courses(
    query_embedding vector(768),
    match_count int default 10
)
returns setof public.courses

language sql stable
as $$
    select *
    from public.courses
    where embedding is not null
    order by embedding <=> query_embedding
    limit match_count;
$$;

-- =========================
-- roadmaps (linked to user skills)
-- =========================
-- A roadmap stores the full week-by-week learning plan generated by Gemini
-- as a single JSONB document (`plan`). The skill analysis is read from
-- `user_skill_details` at generation time, so it is NOT duplicated here.
--
-- Each roadmap is linked to:
--   * public.users(user_id)          -> the employee who owns the roadmap
--   * public.user_skill_details(skill_id) -> the skill analysis that produced it
-- These tables are maintained by Team 1; this script only references them.
create table if not exists public.roadmaps (
    roadmap_id        uuid primary key default gen_random_uuid(),
    user_id           uuid not null references public.users(user_id) on delete cascade,
    skill_id          uuid not null references public.user_skill_details(skill_id) on delete cascade,
    target_role       varchar(100),
    status            varchar(20) not null default 'active',
    plan              jsonb not null default '{}'::jsonb,
    created_at        timestamptz default now(),
    updated_at        timestamptz default now()
);

create index if not exists ix_roadmaps_user_id
  on public.roadmaps (user_id);

create index if not exists ix_roadmaps_user_skill
  on public.roadmaps (user_id, skill_id);

create index if not exists ix_roadmaps_skill_id
  on public.roadmaps (skill_id);