"""Pydantic schemas for the recommendation (learning-roadmap) flow.

The flow has two request/response shapes:

* ``RoadmapPlan`` (and its nested ``WeekPlan`` / ``RoadmapCourseRef``) - the
  week-by-week plan produced by Gemini and stored as a JSONB document.
* ``RoadmapResponse`` - the persisted roadmap returned by the generate and fetch
  endpoints.

No request-body schema is needed for generation: ``skill_id`` is read from the
URL path and all analysis fields are fetched from ``user_skill_details``.
"""

from datetime import datetime
from typing import Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class RoadmapCourseRef(BaseModel):
    """A course referenced inside a week of the roadmap. Mirrors the relevant
    subset of the ``courses`` table row selected via vector search."""

    course_id: UUID
    course_name: str
    provider: Optional[str] = None
    url: Optional[str] = None
    duration_hours: Optional[float] = None
    skills_taught: List[str] = Field(default_factory=list)


class WeekPlan(BaseModel):
    """One week of the learning roadmap."""

    week: int
    focus: str
    skills: List[str] = Field(default_factory=list)
    courses: List[RoadmapCourseRef] = Field(default_factory=list)
    activities: List[str] = Field(default_factory=list)


class RoadmapPlan(BaseModel):
    """The full week-by-week learning plan generated by Gemini."""

    summary: str
    total_weeks: int
    weeks: List[WeekPlan] = Field(default_factory=list)


class RoadmapResponse(BaseModel):
    """A persisted roadmap, returned by the save and fetch endpoints."""

    roadmap_id: UUID
    user_id: UUID
    skill_id: Optional[UUID] = None
    current_role: Optional[str] = None
    target_role: Optional[str] = None
    status: str
    plan: RoadmapPlan
    created_at: Optional[datetime] = None
